GET http://localhost:8080/api/security_clearance
Accept: application/json

###
GET http://localhost:8080/api/security_clearance/1
Accept: application/json

###
POST  http://localhost:8080/api/security_clearance/ HTTP/1.1
Content-Type: application/json

{
  "name": "T Clearance"
}